"""initial schema - all 9 tables

Revision ID: d151e2936178
Revises: 
Create Date: 2026-04-15 18:28:47.326765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd151e2936178'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('category_type', sa.Text(), nullable=False),
    sa.Column('household_tier', sa.Text(), nullable=False),
    sa.Column('tax_context', sa.Text(), nullable=False),
    sa.Column('default_split', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'name', name='uq_category_household_name')
    )
    op.create_table('statements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('issuer', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('layout_hash', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=False),
    sa.Column('parse_status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('person_code', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_envelopes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('amount_cad', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'user_id', 'period_year', name='uq_envelope_category_user_year')
    )
    op.create_table('exact_match_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('normalized_merchant', sa.Text(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('responsibility', sa.Text(), nullable=False),
    sa.Column('confirmation_count', sa.Integer(), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'normalized_merchant', name='uq_cache_household_merchant')
    )
    op.create_table('parse_errors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('statement_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('statement_id', sa.String(length=36), nullable=True),
    sa.Column('cash_date', sa.Date(), nullable=False),
    sa.Column('accounting_period_year', sa.Integer(), nullable=False),
    sa.Column('accounting_period_month', sa.Integer(), nullable=False),
    sa.Column('accounting_period_is_override', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('normalized_description', sa.Text(), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('original_currency', sa.Text(), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('fx_rate_source', sa.Text(), nullable=True),
    sa.Column('cad_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('split_method', sa.Text(), nullable=False),
    sa.Column('andrew_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('kristy_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('classifier_confidence', sa.Float(), nullable=True),
    sa.Column('classifier_source', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('is_manually_reviewed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corrections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('prev_category_id', sa.String(length=36), nullable=True),
    sa.Column('new_category_id', sa.String(length=36), nullable=False),
    sa.Column('prev_split_method', sa.Text(), nullable=True),
    sa.Column('new_split_method', sa.Text(), nullable=False),
    sa.Column('corrected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['new_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['prev_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corrections')
    op.drop_table('transactions')
    op.drop_table('parse_errors')
    op.drop_table('exact_match_cache')
    op.drop_table('budget_envelopes')
    op.drop_table('users')
    op.drop_table('statements')
    op.drop_table('categories')
    op.drop_table('households')
    # ### end Alembic commands ###
